# Generated by Django 3.1.4 on 2020-12-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
